# Arquivo de configuração das variáveis

# Função objetivo para otimizações
#  1: NSE : Nash-Sutcliffe
#  2: SSQ : Sum of Squares of Deviation
#  3: RMSE: Root-Mean-Square Error
#  4: KSE : Kling-Gupta

[ObjectiveFunction]
FO = 1

# Tipo de simulação: simulation_flag
# 1: 'Previsoes'      : com previsões meteorológicas
# 2: 'Bola de cristal': com precipitações observadas

[Simulation]
simulation_flag = 1
simulation_days = 1356

[ExportDirectory]
results = Resultados

